"""Decision correspondence & handoff pack — generated deterministically.

build_correspondence() turns a finished review into the artifact the decision
calls for: an information-request letter, a clause-cited rejection rationale,
an investigator handoff memo, or a short approval record. It is a pure
template over existing data:

- item content comes verbatim from findings (title / explanation),
- quotes come from the validated document citations and finding evidence,
- clause titles and text come from the validated policy citations,
- resolution hints come from the fixed mapping in hints.py.

The function deliberately does NOT receive the Gemini explanation (or any
other LLM output), so no narrative — adversarial or otherwise — can reach the
artifact. Conflicting values are always all preserved; the builder never
selects one as correct.
"""

from __future__ import annotations

import re
from typing import Literal, Optional

from pydantic import BaseModel, Field

from claimiq.data.schemas import ClaimBundle
from claimiq.engine.schemas import (
    ClaimReview,
    Finding,
    FindingCategory,
    FindingEffect,
    Severity,
)
from claimiq.rag.citations import DocumentCitation, PolicyCitation
from claimiq.record.hints import resolution_hints

# ---------------------------------------------------------------------------
# Presentation labels (mirror the Phase 9 frontend helpers; raw IDs secondary)
# ---------------------------------------------------------------------------

DOC_LABELS = {
    "claim_form": "Claim Form",
    "repair_estimate": "Repair Estimate",
    "fir": "FIR / Police Complaint",
    "incident_description": "Incident Description",
}

DECISION_LABELS = {
    "APPROVE": "Approve",
    "REJECT": "Reject",
    "REQUEST_INFORMATION": "Request Information",
    "ESCALATE": "Escalate for Review",
}


def _num(raw_id: str) -> str:
    digits = re.sub(r"\D", "", raw_id)
    return digits.lstrip("0").zfill(2) if digits else raw_id


def label_claim(claim_id: str) -> str:
    return f"Claim {_num(claim_id)}" if claim_id.startswith("CLM-") else claim_id


def label_clause(clause_id: str) -> str:
    return f"Policy Clause {_num(clause_id)}" if clause_id.startswith("POL-") else clause_id


def label_finding(finding_id: str) -> str:
    return f"Finding {_num(finding_id)}" if finding_id.startswith("FIND-") else finding_id


def doc_label(doc_type: str) -> str:
    return DOC_LABELS.get(doc_type, doc_type.replace("_", " ").title())


_DOC_TOKEN_RE = re.compile(r"\b(" + "|".join(DOC_LABELS) + r")\b")


def _pretty(text: str) -> str:
    """Swap raw doc-type tokens in engine text for their human labels.

    Whole-word only — 'fir' inside 'confirmed' must never be replaced.
    """
    return _DOC_TOKEN_RE.sub(lambda m: DOC_LABELS[m.group(1)], text)


# ---------------------------------------------------------------------------
# Artifact structure
# ---------------------------------------------------------------------------


class EvidenceLine(BaseModel):
    """One evidence value inside an artifact item — always from stored refs."""

    source: str  # document | policy_schedule | claim_metadata
    doc_type: str = ""  # set when source == document
    label: str  # "Claim Form" / "Policy Schedule (trusted record)"
    value: str
    quote: Optional[str] = None
    quote_verified: bool = False


class RecordItem(BaseModel):
    heading: str = ""
    body: list[str] = Field(default_factory=list)
    evidence: list[EvidenceLine] = Field(default_factory=list)
    policy_basis: list[str] = Field(default_factory=list)  # "Policy Clause 07 — Title (POL-07)"
    clause_ids: list[str] = Field(default_factory=list)
    finding_id: str = ""
    hints: list[str] = Field(default_factory=list)
    conflict: bool = False


class RecordSection(BaseModel):
    title: str
    paragraphs: list[str] = Field(default_factory=list)
    items: list[RecordItem] = Field(default_factory=list)
    numbered: bool = False


CorrespondenceKind = Literal[
    "information_request",
    "decision_rationale",
    "investigator_handoff",
    "approval_record",
]


class Correspondence(BaseModel):
    kind: CorrespondenceKind
    doc_title: str
    claim_label: str
    claim_id: str
    decision: str
    decision_label: str
    generated_note: str
    sections: list[RecordSection]
    text: str  # canonical plain-text rendering of the sections above


GENERATED_NOTE = (
    "Generated by ClaimIQ from the deterministic review record. Every statement "
    "above is traceable to a finding, a cited document quote, or the policy "
    "text; no part of this document was written by a language model."
)


# ---------------------------------------------------------------------------
# Shared assembly helpers
# ---------------------------------------------------------------------------


def _clause_map(policy_citations: list[PolicyCitation]) -> dict[str, PolicyCitation]:
    return {c.clause_id: c for c in policy_citations if c.valid}


def _policy_basis(finding: Finding, clauses: dict[str, PolicyCitation]) -> list[str]:
    lines = []
    for cid in finding.clause_ids:
        c = clauses.get(cid)
        if c is not None:  # never invent a clause the citations don't validate
            lines.append(f"{label_clause(cid)} — {c.title} ({cid})")
    return lines


def _evidence_lines(finding: Finding, schedule_label: str = "Policy Schedule (trusted record)") -> list[EvidenceLine]:
    lines: list[EvidenceLine] = []
    seen: set[tuple] = set()
    for ref in finding.evidence:
        key = (ref.source, ref.doc_type.value if ref.doc_type else "", ref.field, ref.value)
        if key in seen:
            continue
        seen.add(key)
        if ref.source == "document" and ref.doc_type is not None:
            lines.append(EvidenceLine(
                source="document", doc_type=ref.doc_type.value,
                label=doc_label(ref.doc_type.value), value=ref.value,
                quote=ref.quote, quote_verified=bool(ref.quote_verified),
            ))
        elif ref.source == "policy_schedule":
            lines.append(EvidenceLine(
                source="policy_schedule", label=schedule_label, value=ref.value,
            ))
        # claim_metadata refs (e.g. the raw submitted-documents list) are
        # bookkeeping, not correspondence content — deliberately omitted.
    return lines


def _citation_lines(finding_id: str, doc_citations: list[DocumentCitation]) -> list[EvidenceLine]:
    lines: list[EvidenceLine] = []
    seen: set[tuple] = set()
    for c in doc_citations:
        if c.finding_id != finding_id or not c.valid:
            continue
        key = (c.doc_type, c.field, c.value, c.quote or "")
        if key in seen:
            continue
        seen.add(key)
        lines.append(EvidenceLine(
            source="document", doc_type=c.doc_type, label=doc_label(c.doc_type),
            value=c.value, quote=c.quote, quote_verified=c.quote_verified,
        ))
    return lines


def _findings_by_effect(review: ClaimReview, effect: FindingEffect) -> list[Finding]:
    return [f for f in review.findings if f.effect == effect]


def _received_documents(bundle: ClaimBundle) -> str:
    return ", ".join(doc_label(d.doc_type.value) for d in bundle.documents)


# ---------------------------------------------------------------------------
# Artifact builders — one per decision
# ---------------------------------------------------------------------------


def _build_information_request(
    bundle: ClaimBundle, review: ClaimReview,
    doc_citations: list[DocumentCitation], clauses: dict[str, PolicyCitation],
) -> tuple[str, list[RecordSection]]:
    needed = _findings_by_effect(review, FindingEffect.NEEDS_INFORMATION)
    items = []
    for f in needed:
        items.append(RecordItem(
            heading=_pretty(f.title),
            body=[_pretty(f.explanation)],
            evidence=_citation_lines(f.finding_id, doc_citations),
            policy_basis=_policy_basis(f, clauses),
            clause_ids=list(f.clause_ids),
            finding_id=f.finding_id,
        ))
    sections = [
        RecordSection(
            title="Regarding your claim",
            paragraphs=[
                f"Dear {bundle.policy_schedule.policyholder},",
                f"We are reviewing {label_claim(review.claim_id)} "
                f"({review.claim_type} claim, reported {bundle.submitted_at}). "
                f"Documents received so far: {_received_documents(bundle)}.",
                "The review cannot proceed to a final assessment yet, because the "
                "information below is missing from the submitted file.",
            ],
        ),
        RecordSection(title="Information required", items=items, numbered=True),
        RecordSection(
            title="Next step",
            paragraphs=[
                "Please provide all of the requested items in one submission so the "
                "claim can proceed to the next stage of review.",
                "This is a request for information only — no assessment outcome has "
                "been reached, and this letter does not decide the claim.",
            ],
        ),
    ]
    return "Information Request", sections


def _build_decision_rationale(
    bundle: ClaimBundle, review: ClaimReview,
    doc_citations: list[DocumentCitation], clauses: dict[str, PolicyCitation],
) -> tuple[str, list[RecordSection]]:
    grounds = _findings_by_effect(review, FindingEffect.BLOCK_REJECT)
    items = []
    for f in grounds:
        items.append(RecordItem(
            heading=_pretty(f.title),
            body=[_pretty(f.explanation)],
            evidence=_citation_lines(f.finding_id, doc_citations),
            policy_basis=_policy_basis(f, clauses),
            clause_ids=list(f.clause_ids),
            finding_id=f.finding_id,
        ))
    # The clauses the rejection rests on, quoted verbatim from the policy.
    clause_items = []
    seen: set[str] = set()
    for f in grounds:
        for cid in f.clause_ids:
            c = clauses.get(cid)
            if c is None or cid in seen:
                continue
            seen.add(cid)
            clause_items.append(RecordItem(
                heading=f"{label_clause(cid)} — {c.title} ({cid})",
                body=[c.text],
            ))
    sections = [
        RecordSection(
            title="Decision",
            paragraphs=[
                f"{label_claim(review.claim_id)} ({review.claim_type} claim, reported "
                f"{bundle.submitted_at}) — decision: {DECISION_LABELS['REJECT']}.",
                _pretty(review.decision_rationale),
            ],
        ),
        RecordSection(
            title="Grounds, with evidence and policy basis",
            items=items, numbered=True,
        ),
        RecordSection(title="Policy provisions applied (verbatim)", items=clause_items),
        RecordSection(
            title="Record note",
            paragraphs=[
                "Each ground above is a deterministic finding citing the submitted "
                "evidence and the specific policy clause it engages. Statements "
                "quoted from documents were verified verbatim against the source "
                "text unless marked otherwise.",
                "Final authority for the decision, and for handling any "
                "representation against it, rests with the claims handler.",
            ],
        ),
    ]
    return "Decision Rationale — Rejection", sections


def _build_investigator_handoff(
    bundle: ClaimBundle, review: ClaimReview,
    doc_citations: list[DocumentCitation], clauses: dict[str, PolicyCitation],
) -> tuple[str, list[RecordSection]]:
    established = [
        f for f in review.findings
        if f.severity == Severity.INFO and f.effect == FindingEffect.NONE
    ]
    conflicts = [f for f in review.findings if f.category == FindingCategory.CONTRADICTION]
    driving = [f for fid in review.decision_reasons
               if (f := review.finding(fid)) is not None]
    other_reasons = [f for f in driving if f.category != FindingCategory.CONTRADICTION]

    conflict_items = []
    for f in conflicts:
        conflict_items.append(RecordItem(
            heading=_pretty(f.title),
            body=[_pretty(f.explanation)],
            evidence=_evidence_lines(f),  # every version, no side chosen
            policy_basis=_policy_basis(f, clauses),
            clause_ids=list(f.clause_ids),
            finding_id=f.finding_id,
            hints=resolution_hints(f),
            conflict=True,
        ))

    reason_items = [
        RecordItem(
            heading=_pretty(f.title),
            body=[_pretty(f.explanation)],
            evidence=_citation_lines(f.finding_id, doc_citations),
            policy_basis=_policy_basis(f, clauses),
            clause_ids=list(f.clause_ids),
            finding_id=f.finding_id,
        )
        for f in other_reasons
    ]

    # Aggregate hints across all conflicts, deduplicated in order.
    all_hints: list[str] = []
    for f in conflicts:
        for h in resolution_hints(f):
            if h not in all_hints:
                all_hints.append(h)

    clause_items = []
    seen: set[str] = set()
    for f in driving:
        for cid in f.clause_ids:
            c = clauses.get(cid)
            if c is None or cid in seen:
                continue
            seen.add(cid)
            clause_items.append(RecordItem(
                heading=f"{label_clause(cid)} — {c.title} ({cid})",
                body=[c.text],
            ))

    n_checks = len(review.checks_run or [])
    n_info = len(established)
    n_issues = len([f for f in review.findings if f.severity != Severity.INFO])

    sections = [
        RecordSection(
            title="Review status",
            paragraphs=[
                f"{label_claim(review.claim_id)} ({review.claim_type} claim, reported "
                f"{bundle.submitted_at}) — {DECISION_LABELS['ESCALATE']}.",
                _pretty(review.decision_rationale),
            ],
        ),
        RecordSection(
            title="Established information",
            paragraphs=[] if established else [
                "No check recorded a fully satisfied result for this claim."
            ],
            items=[RecordItem(heading=_pretty(f.title), finding_id=f.finding_id)
                   for f in established],
        ),
    ]
    if conflict_items:
        sections.append(RecordSection(
            title="Conflicting information (all versions preserved — none assumed correct)",
            items=conflict_items,
        ))
    sections.append(RecordSection(
        title="Why human review is required",
        items=(
            [RecordItem(heading=_pretty(f.title), finding_id=f.finding_id)
             for f in driving]
            if not (conflict_items or reason_items)
            else [RecordItem(
                heading=_pretty(f.title),
                body=[_pretty(f.explanation)] if f.category != FindingCategory.CONTRADICTION else
                     ["See the conflict detail above."],
                finding_id=f.finding_id,
            ) for f in driving]
        ),
        numbered=True,
    ))
    if all_hints:
        sections.append(RecordSection(
            title="What would help resolve the case",
            paragraphs=[
                "These additional records could help establish the contested facts. "
                "They are suggestions for the investigator — the conflicts themselves "
                "are not resolved by this review."
            ],
            items=[RecordItem(heading=h) for h in all_hints],
        ))
    if clause_items:
        sections.append(RecordSection(
            title="Applicable policy clauses (verbatim)", items=clause_items,
        ))
    sections.append(RecordSection(
        title="Review scope",
        paragraphs=[
            f"{n_checks} deterministic checks were run: {n_issues} finding(s) flag "
            f"issues and {n_info} record a satisfied condition.",
            "Document authenticity, licence validity against the transport registry, "
            "and discretionary decisions such as condoning timing issues remain "
            "outside this automated review.",
        ],
    ))
    return "Investigator Handoff", sections


def _build_approval_record(
    bundle: ClaimBundle, review: ClaimReview,
    doc_citations: list[DocumentCitation], clauses: dict[str, PolicyCitation],
) -> tuple[str, list[RecordSection]]:
    positives = [f for fid in review.decision_reasons
                 if (f := review.finding(fid)) is not None]
    items = [
        RecordItem(
            heading=_pretty(f.title),
            policy_basis=_policy_basis(f, clauses),
            clause_ids=list(f.clause_ids),
            finding_id=f.finding_id,
        )
        for f in positives
    ]
    sections = [
        RecordSection(
            title="Review outcome",
            paragraphs=[
                f"{label_claim(review.claim_id)} ({review.claim_type} claim, reported "
                f"{bundle.submitted_at}) — recommendation: {DECISION_LABELS['APPROVE']}.",
                _pretty(review.decision_rationale),
            ],
        ),
        RecordSection(title="Conditions established by the review", items=items, numbered=True),
        RecordSection(
            title="Record note",
            paragraphs=[
                "This review is a recommendation produced by deterministic checks "
                "over the extracted evidence. Settlement, quantum and final approval "
                "authority rest with the claims handler.",
            ],
        ),
    ]
    return "Review Record — Approval", sections


# ---------------------------------------------------------------------------
# Plain-text rendering (the canonical copy/download form)
# ---------------------------------------------------------------------------


def _render_text(corr_title: str, review: ClaimReview, sections: list[RecordSection]) -> str:
    lines: list[str] = []
    lines.append(corr_title.upper())
    lines.append("")
    lines.append(f"{label_claim(review.claim_id)}  ({review.claim_id})")
    lines.append(f"Review outcome: {DECISION_LABELS.get(review.decision.value, review.decision.value)}")
    lines.append(f"Review date: {review.reviewed_at.date().isoformat()}")
    for section in sections:
        lines.append("")
        lines.append(section.title.upper())
        for p in section.paragraphs:
            lines.append(p)
        for i, item in enumerate(section.items, start=1):
            prefix = f"{i}. " if section.numbered else "- "
            if item.heading:
                lines.append(f"{prefix}{item.heading}")
            indent = "   " if section.numbered else "  "
            for b in item.body:
                lines.append(f"{indent}{b}")
            for ev in item.evidence:
                lines.append(f"{indent}{ev.label}: {ev.value}")
                if ev.quote:
                    flag = "" if ev.quote_verified else "  [quote not verified against the source]"
                    lines.append(f'{indent}  "{ev.quote}"{flag}')
            for basis in item.policy_basis:
                lines.append(f"{indent}Policy basis: {basis}")
            if item.hints:
                lines.append(f"{indent}What would help resolve this:")
                for h in item.hints:
                    lines.append(f"{indent}  - {h}")
            if item.finding_id:
                lines.append(f"{indent}Ref: {label_finding(item.finding_id)} ({item.finding_id})")
    lines.append("")
    lines.append("-" * 8)
    lines.append(GENERATED_NOTE)
    lines.append(f"Engine v{review.engine_version} · {review.claim_id}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

_BUILDERS = {
    "REQUEST_INFORMATION": ("information_request", _build_information_request),
    "REJECT": ("decision_rationale", _build_decision_rationale),
    "ESCALATE": ("investigator_handoff", _build_investigator_handoff),
    "APPROVE": ("approval_record", _build_approval_record),
}


def build_correspondence(
    bundle: ClaimBundle,
    review: ClaimReview,
    document_citations: list[DocumentCitation],
    policy_citations: list[PolicyCitation],
) -> Correspondence:
    """Build the artifact matching the review's decision.

    Pure and deterministic: same review in, same artifact out. Raises only on
    caller bugs (mismatched claim ids), never on claim content.
    """
    if bundle.claim_id != review.claim_id:
        raise ValueError(
            f"bundle is {bundle.claim_id!r} but review is {review.claim_id!r}"
        )
    kind, builder = _BUILDERS[review.decision.value]
    clauses = _clause_map(policy_citations)
    doc_title, sections = builder(bundle, review, document_citations, clauses)
    return Correspondence(
        kind=kind,
        doc_title=doc_title,
        claim_label=label_claim(review.claim_id),
        claim_id=review.claim_id,
        decision=review.decision.value,
        decision_label=DECISION_LABELS.get(review.decision.value, review.decision.value),
        generated_note=GENERATED_NOTE,
        sections=sections,
        text=_render_text(doc_title, review, sections),
    )
